// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefConflictLegacy {
    #[deprecated]
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub removes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[deprecated]
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub adds: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// This is redundant with `RefTargetTerm`. It exists for historical reasons.
/// TODO: Consider deprecating it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefConflict {
    #[prost(message, repeated, tag = "1")]
    pub removes: ::prost::alloc::vec::Vec<ref_conflict::Term>,
    #[prost(message, repeated, tag = "2")]
    pub adds: ::prost::alloc::vec::Vec<ref_conflict::Term>,
}
/// Nested message and enum types in `RefConflict`.
pub mod ref_conflict {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Term {
        #[prost(bytes = "vec", optional, tag = "1")]
        pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    }
}
/// RefTarget that may be serialized in legacy form.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefTarget {
    /// New `RefConflict` type represents both `commit_id` and `conflict_legacy`.
    #[prost(oneof = "ref_target::Value", tags = "1, 2, 3")]
    pub value: ::core::option::Option<ref_target::Value>,
}
/// Nested message and enum types in `RefTarget`.
pub mod ref_target {
    /// New `RefConflict` type represents both `commit_id` and `conflict_legacy`.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[deprecated]
        #[prost(bytes, tag = "1")]
        CommitId(::prost::alloc::vec::Vec<u8>),
        #[deprecated]
        #[prost(message, tag = "2")]
        ConflictLegacy(super::RefConflictLegacy),
        #[prost(message, tag = "3")]
        Conflict(super::RefConflict),
    }
}
/// RefTarget term that should be serialized in native form, in which positive
/// and negative terms alternate.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefTargetTerm {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteBookmark {
    #[prost(string, tag = "1")]
    pub remote_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<RefTarget>,
    /// Introduced in jj 0.11.
    #[prost(enumeration = "RemoteRefState", optional, tag = "3")]
    pub state: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bookmark {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unset if the bookmark has been deleted locally.
    #[prost(message, optional, tag = "2")]
    pub local_target: ::core::option::Option<RefTarget>,
    /// Deprecated since jj 0.34.
    #[deprecated]
    #[prost(message, repeated, tag = "3")]
    pub remote_bookmarks: ::prost::alloc::vec::Vec<RemoteBookmark>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitRef {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// This field is just for historical reasons (before we had the RefTarget
    /// type). New GitRefs have (only) the target field.
    /// TODO: Delete support for the old format.
    #[deprecated]
    #[prost(bytes = "vec", tag = "2")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub target: ::core::option::Option<RefTarget>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitHead {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<RefTarget>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteRef {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub target_terms: ::prost::alloc::vec::Vec<RefTargetTerm>,
    #[prost(enumeration = "RemoteRefState", tag = "3")]
    pub state: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<RefTarget>,
}
/// Configuration IDs use the same alternating positive/negative order as
/// RefTargetTerm. An absent value represents an unregistered configuration.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SparsePatternTerm {
    #[prost(bytes = "vec", optional, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WcSparsePatterns {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<SparsePatternTerm>,
    /// Required discriminator: experimental expression-string entries used zero.
    #[prost(uint32, tag = "3")]
    pub version: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct View {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub head_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[deprecated]
    #[prost(bytes = "vec", tag = "2")]
    pub wc_commit_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, bytes", tag = "8")]
    pub wc_commit_ids: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
    /// Local bookmarks and remote bookmarks in legacy form.
    #[prost(message, repeated, tag = "5")]
    pub bookmarks: ::prost::alloc::vec::Vec<Bookmark>,
    #[prost(message, repeated, tag = "6")]
    pub local_tags: ::prost::alloc::vec::Vec<Tag>,
    /// Introduced in jj 0.34.
    #[prost(message, repeated, tag = "11")]
    pub remote_views: ::prost::alloc::vec::Vec<RemoteView>,
    /// Only a subset of the refs. For example, does not include refs/notes/.
    #[prost(message, repeated, tag = "3")]
    pub git_refs: ::prost::alloc::vec::Vec<GitRef>,
    /// This field is just for historical reasons (before we had the RefTarget
    /// type). New Views have (only) the target field.
    /// TODO: Delete support for the old format.
    #[deprecated]
    #[prost(bytes = "vec", tag = "7")]
    pub git_head_legacy: ::prost::alloc::vec::Vec<u8>,
    #[deprecated]
    #[prost(message, optional, tag = "9")]
    pub git_head: ::core::option::Option<RefTarget>,
    /// Whether "@git" tags have been migrated to remote_views.
    #[prost(bool, tag = "12")]
    pub has_git_refs_migrated_to_remote_tags: bool,
    /// Per-workspace Git HEAD targets, keyed by workspace name.
    #[prost(message, repeated, tag = "13")]
    pub git_heads: ::prost::alloc::vec::Vec<GitHead>,
    /// Desired sparse selections keyed by workspace, including unresolved merges.
    #[prost(message, repeated, tag = "14")]
    pub wc_sparse_patterns: ::prost::alloc::vec::Vec<WcSparsePatterns>,
    #[prost(message, optional, tag = "15")]
    pub project_metadata: ::core::option::Option<ProjectMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteView {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub bookmarks: ::prost::alloc::vec::Vec<RemoteRef>,
    #[prost(message, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<RemoteRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Operation {
    #[prost(bytes = "vec", tag = "1")]
    pub view_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub parents: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<OperationMetadata>,
    /// Introduced in jj 0.30.
    #[prost(message, repeated, tag = "4")]
    pub commit_predecessors: ::prost::alloc::vec::Vec<CommitPredecessors>,
    /// Whether or not `commit_predecessors` is recorded.
    #[prost(bool, tag = "5")]
    pub stores_commit_predecessors: bool,
}
/// TODO: Share with store.proto? Do we even need the timezone here?
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub millis_since_epoch: i64,
    #[prost(int32, tag = "2")]
    pub tz_offset: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OperationMetadata {
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<Timestamp>,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_snapshot: bool,
    #[prost(string, optional, tag = "8")]
    pub workspace_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "6")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommitPredecessors {
    #[prost(bytes = "vec", tag = "1")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub predecessor_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectMetadata {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, repeated, tag = "2")]
    pub projects: ::prost::alloc::vec::Vec<ProjectEntry>,
    #[prost(message, repeated, tag = "3")]
    pub bindings: ::prost::alloc::vec::Vec<BindingEntry>,
    #[prost(message, repeated, tag = "4")]
    pub labels: ::prost::alloc::vec::Vec<LabelEntry>,
    #[prost(message, repeated, tag = "5")]
    pub connections: ::prost::alloc::vec::Vec<ConnectionEntry>,
    #[prost(message, repeated, tag = "6")]
    pub observations: ::prost::alloc::vec::Vec<ObservationEntry>,
    #[prost(message, repeated, tag = "7")]
    pub remote_names: ::prost::alloc::vec::Vec<ScopedRemoteNameEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScopedRemoteName {
    #[prost(bytes = "vec", tag = "1")]
    pub project_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScopedRemoteNameTerm {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<ScopedRemoteName>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScopedRemoteNameEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub connection_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<ScopedRemoteNameTerm>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectRecord {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub canonical_root: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindingRecord {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub project_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag = "2")]
    pub repository_view: bool,
    #[prost(bytes = "vec", tag = "3")]
    pub connection_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub provider: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub version: u32,
    #[prost(uint32, tag = "6")]
    pub representation: u32,
    #[prost(string, tag = "7")]
    pub expression: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "8")]
    pub base: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectTerm {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<ProjectRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BindingTerm {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<BindingRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdTerm {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<ProjectTerm>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindingEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<BindingTerm>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LabelEntry {
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<IdTerm>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionEntry {
    #[prost(string, tag = "1")]
    pub remote: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub terms: ::prost::alloc::vec::Vec<IdTerm>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversionTerm {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub canonical: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "2")]
    pub raw: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversionObservation {
    #[prost(bytes = "vec", tag = "1")]
    pub binding_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub binding: ::core::option::Option<BindingRecord>,
    #[prost(bytes = "vec", tag = "3")]
    pub connection_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub raw_ref: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub terms: ::prost::alloc::vec::Vec<ConversionTerm>,
    #[prost(string, optional, tag = "7")]
    pub base: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub generation: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObservationTerm {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<ConversionObservation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObservationEntry {
    #[prost(string, tag = "1")]
    pub remote: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub terms: ::prost::alloc::vec::Vec<ObservationTerm>,
    #[prost(enumeration = "ObservationKind", tag = "5")]
    pub kind: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RemoteRefState {
    New = 0,
    Tracked = 1,
}
impl RemoteRefState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::New => "New",
            Self::Tracked => "Tracked",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "New" => Some(Self::New),
            "Tracked" => Some(Self::Tracked),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObservationKind {
    Unknown = 0,
    Bookmark = 1,
    Tag = 2,
    Revision = 3,
}
impl ObservationKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "OBSERVATION_KIND_UNKNOWN",
            Self::Bookmark => "OBSERVATION_KIND_BOOKMARK",
            Self::Tag => "OBSERVATION_KIND_TAG",
            Self::Revision => "OBSERVATION_KIND_REVISION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBSERVATION_KIND_UNKNOWN" => Some(Self::Unknown),
            "OBSERVATION_KIND_BOOKMARK" => Some(Self::Bookmark),
            "OBSERVATION_KIND_TAG" => Some(Self::Tag),
            "OBSERVATION_KIND_REVISION" => Some(Self::Revision),
            _ => None,
        }
    }
}
