// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Configuration {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<Rule>,
    #[prost(message, repeated, tag = "3")]
    pub mappings: ::prost::alloc::vec::Vec<Mapping>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rule {
    #[prost(bool, tag = "1")]
    pub include: bool,
    #[prost(message, optional, tag = "2")]
    pub expression: ::core::option::Option<Expression>,
}
/// Kind and arity are checked strictly by the domain decoder.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expression {
    #[prost(enumeration = "expression::Kind", tag = "1")]
    pub kind: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub glob: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub case_insensitive: bool,
    #[prost(message, repeated, tag = "5")]
    pub children: ::prost::alloc::vec::Vec<Expression>,
}
/// Nested message and enum types in `Expression`.
pub mod expression {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        None = 0,
        All = 1,
        FilePath = 2,
        PrefixPath = 3,
        FileGlob = 4,
        PrefixGlob = 5,
        Union = 6,
        Intersection = 7,
        Difference = 8,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "NONE",
                Self::All => "ALL",
                Self::FilePath => "FILE_PATH",
                Self::PrefixPath => "PREFIX_PATH",
                Self::FileGlob => "FILE_GLOB",
                Self::PrefixGlob => "PREFIX_GLOB",
                Self::Union => "UNION",
                Self::Intersection => "INTERSECTION",
                Self::Difference => "DIFFERENCE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NONE" => Some(Self::None),
                "ALL" => Some(Self::All),
                "FILE_PATH" => Some(Self::FilePath),
                "PREFIX_PATH" => Some(Self::PrefixPath),
                "FILE_GLOB" => Some(Self::FileGlob),
                "PREFIX_GLOB" => Some(Self::PrefixGlob),
                "UNION" => Some(Self::Union),
                "INTERSECTION" => Some(Self::Intersection),
                "DIFFERENCE" => Some(Self::Difference),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mapping {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub recursive: bool,
}
